services:
  db:
    image: mariadb:10.6 
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root_db_nextcloud
      MYSQL_DATABASE: $(MYSQL_DATABASE)
      MYSQL_USER: $(MYSQL_USER)
      MYSQL_PASSWORD: $(MYSQL_PASSWORD)

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always

  app:
    image: nextcloud:fpm 
    container_name: nextcloud_app
    restart: always
    volumes:
      - ./nextcloud_data:/var/www/html # <-- installation path
      - /your/photos/path:/var/www/html/data/YOUR_USERNAME/files/Photos     
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: $(MYSQL_DATABASE)
      MYSQL_USER: $(MYSQL_USER)
      MYSQL_PASSWORD: $(MYSQL_PASSWORD)
      REDIS_HOST: redis
      PHP_MEMORY_LIMIT: 512M
      
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine 
    container_name: nextcloud_web
    restart: always
    ports:
      - "8080:80" 
                  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nextcloud.conf:ro
      - ./nextcloud_data:/var/www/html:ro
    depends_on:
      - app
