services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: ${PHOTOPRISM_ADMIN_USER} # Inside your .env
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD} # Inside your .env
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_DSN: photoprism:${DB_PASSWORD}@tcp(database:3306)/photoprism?charset=utf8mb4&parseTime=true
      PHOTOPRISM_HTTP_COMPRESSION: "true"
      PHOTOPRISM_INDEX_SCHEDULE: "@every 10m" # <- index rate
      PHOTOPRISM_SCAN_INTERVAL: "600" 

    volumes:
      - ./storage:/photoprism/storage
      - /your/photos/path:/photoprism/originals
    depends_on:
      - database

  database:
    image: mariadb:10.6
    container_name: photoprism_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: "1" # Keep this line
    volumes:
      - ./database:/var/lib/mysql
